on:
  schedule:
    - cron: "40 13 * * *"
  workflow_dispatch:

jobs:
  jobs1:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set execute permission for main.sh
        run: chmod +x main.sh
        working-directory: /Users/loctek/code/Irene/miniature-funicular/main.sh   
      - run: bash main.sh
        working-directory: /Users/loctek/code/Irene/miniature-funicular/main.sh